import { Prop, Schema, SchemaFactory } from '@nestjs/mongoose';
import { HydratedDocument, Schema as MongooseSchema } from 'mongoose';
import { EntityDocumentHelper } from '../../../../../utils/document-entity-helper';
import { tenantFilterPlugin } from '../../../../../common/plugins/tenant-filter.plugin';

export type TicketMessageDocument = HydratedDocument<TicketMessageSchemaClass>;

/**
 * What an entry on a ticket is.
 *
 * - `reply`  — visible to the customer. This is the only kind that satisfies a
 *              first-response SLA.
 * - `note`   — internal. Never leaves the tenant; masked from any customer-facing
 *              surface by construction, because no such surface reads it.
 * - `system` — generated by the platform: status changes, assignment, merge,
 *              SLA breach, escalation.
 */
export const TICKET_MESSAGE_KINDS = ['reply', 'note', 'system'] as const;
export type TicketMessageKind = (typeof TICKET_MESSAGE_KINDS)[number];

/** Who produced the entry. `customer` arrives from the linked conversation. */
export const TICKET_MESSAGE_AUTHOR_TYPES = [
  'agent',
  'customer',
  'system',
] as const;
export type TicketMessageAuthorType =
  (typeof TICKET_MESSAGE_AUTHOR_TYPES)[number];

@Schema({
  timestamps: true,
  collection: 'ticket_messages',
  toJSON: { virtuals: true, getters: true },
})
export class TicketMessageSchemaClass extends EntityDocumentHelper {
  @Prop({
    type: MongooseSchema.Types.ObjectId,
    ref: 'TenantSchemaClass',
    required: true,
    index: true,
  })
  tenantId: string;

  @Prop({
    type: MongooseSchema.Types.ObjectId,
    ref: 'TicketSchemaClass',
    required: true,
    index: true,
  })
  ticketId: string;

  @Prop({ type: String, enum: TICKET_MESSAGE_KINDS, required: true })
  kind: TicketMessageKind;

  @Prop({
    type: String,
    enum: TICKET_MESSAGE_AUTHOR_TYPES,
    required: true,
  })
  authorType: TicketMessageAuthorType;

  /** Null for `system` entries, which no user authored. */
  @Prop({
    type: MongooseSchema.Types.ObjectId,
    ref: 'UserSchemaClass',
    default: null,
  })
  authorId?: string | null;

  @Prop({ required: true })
  body: string;

  /**
   * References into the `files` collection.
   *
   * Ids only — name and size are read through the files API, which is where
   * the ACL, the signed download and the storage quota already live. Copying
   * them here would create a second, staler description of the same object.
   */
  @Prop({
    type: [{ type: MongooseSchema.Types.ObjectId, ref: 'FileSchemaClass' }],
    default: [],
  })
  attachmentIds: string[];

  /**
   * Machine-readable detail for `system` entries — `{ event, from, to, ... }`.
   *
   * The rendered sentence is built client-side from this, so the timeline
   * reads in the viewer's language rather than in whatever language the server
   * happened to run in when the event fired.
   */
  @Prop({ type: MongooseSchema.Types.Mixed, default: null })
  systemPayload?: Record<string, unknown> | null;

  @Prop()
  editedAt?: Date;

  @Prop()
  deletedAt?: Date;

  @Prop({ type: MongooseSchema.Types.ObjectId, ref: 'UserSchemaClass' })
  createdById?: string;

  createdAt: Date;
  updatedAt: Date;
}

export const TicketMessageSchema = SchemaFactory.createForClass(
  TicketMessageSchemaClass,
);

TicketMessageSchema.plugin(tenantFilterPlugin, { field: 'tenantId' });

// The one query this collection exists to serve: a ticket's timeline, newest
// last, paginated by cursor. `deletedAt` is in the key so a redacted note does
// not force the scan to fetch and discard.
TicketMessageSchema.index(
  { tenantId: 1, ticketId: 1, deletedAt: 1, createdAt: 1, _id: 1 },
  { name: 'ticket_timeline' },
);

// Backs "has this ticket ever had an agent reply", used by the first-response
// projection and by the reply-window check.
TicketMessageSchema.index(
  { tenantId: 1, ticketId: 1, kind: 1, createdAt: 1 },
  { name: 'ticket_message_kind' },
);
