export const OMNI_ERRORS = {
  CONVERSATION_NOT_FOUND: 'OMNI_CONVERSATION_NOT_FOUND',
  CHANNEL_NOT_FOUND: 'OMNI_CHANNEL_NOT_FOUND',
  REPLY_WINDOW_EXPIRED: 'OMNI_REPLY_WINDOW_EXPIRED',
  CONTENT_REQUIRED: 'OMNI_CONTENT_REQUIRED',
  INVALID_WEBHOOK_SIGNATURE: 'OMNI_INVALID_WEBHOOK_SIGNATURE',
  AGENT_ID_REQUIRED: 'OMNI_AGENT_ID_REQUIRED',
  TAG_REQUIRED: 'OMNI_TAG_REQUIRED',
  CURSOR_INVALID: 'OMNI_CURSOR_INVALID',
  MESSAGE_IDS_EMPTY: 'OMNI_MESSAGE_IDS_EMPTY',
} as const;

export type OmniErrorCode = (typeof OMNI_ERRORS)[keyof typeof OMNI_ERRORS];
