export const USER_ERRORS = {
  NOT_FOUND: 'USER_NOT_FOUND',
  EMAIL_EXISTS: 'USER_EMAIL_EXISTS',
  KEYCLOAK_ID_MISSING: 'USER_KEYCLOAK_ID_MISSING',
  NOT_IN_TENANT: 'USER_NOT_IN_TENANT',
  ALREADY_IN_TENANT: 'USER_ALREADY_IN_TENANT',
} as const;

export type UserErrorCode = (typeof USER_ERRORS)[keyof typeof USER_ERRORS];
