import { Prop, Schema, SchemaFactory } from '@nestjs/mongoose';
import { Document } from 'mongoose';

export type VisitorSessionDocument = VisitorSession & Document;

/**
 * VisitorSession — tracks a livechat widget visitor.
 *
 * Created on first connection, updated on each message.
 * Identity can be enriched post-hoc when the visitor provides an email.
 */
@Schema({ collection: 'livechat_visitor_sessions', timestamps: true })
export class VisitorSession {
  /** Browser fingerprint or UUID generated by the widget on first load */
  @Prop({ required: true, index: true })
  visitorId: string;

  /** Which tenant's widget this visitor is connecting to */
  @Prop({ required: true, index: true })
  tenantId: string;

  /** Associated channel (livechat channel config id) */
  @Prop({ required: true })
  channelId: string;

  /** Active Socket.IO socket ID (updated on reconnect) */
  @Prop()
  socketId?: string;

  /** Optional: enriched when visitor provides email */
  @Prop()
  email?: string;

  /** Optional: enriched visitor display name */
  @Prop()
  name?: string;

  /** Linked CRM contact ID (resolved on email enrichment) */
  @Prop()
  contactId?: string;

  /** Current active conversation ID */
  @Prop({ index: true })
  conversationId?: string;

  /** Session start time */
  @Prop({ default: Date.now })
  startedAt: Date;

  /** Last activity */
  @Prop({ default: Date.now })
  lastSeenAt: Date;

  /** Page URL where the widget is embedded */
  @Prop()
  pageUrl?: string;

  /** User-Agent of the visitor */
  @Prop()
  userAgent?: string;

  /** ISO country code (from IP geo-lookup if enabled) */
  @Prop()
  country?: string;
}

export const VisitorSessionSchema =
  SchemaFactory.createForClass(VisitorSession);
VisitorSessionSchema.index({ visitorId: 1, tenantId: 1 }, { unique: true });
