export const TENANT_ERRORS = {
  NOT_FOUND: 'TENANT_NOT_FOUND',
  ALIAS_TAKEN: 'TENANT_ALIAS_TAKEN',
  CONTEXT_MISSING: 'TENANT_CONTEXT_MISSING',
  SUSPENDED: 'TENANT_SUSPENDED',
  STORAGE_QUOTA_EXCEEDED: 'TENANT_STORAGE_QUOTA_EXCEEDED',
  REGISTRATION_FAILED: 'TENANT_REGISTRATION_FAILED',
} as const;

export type TenantErrorCode =
  (typeof TENANT_ERRORS)[keyof typeof TENANT_ERRORS];
