/**
 * ChannelType — extensible channel identifier.
 *
 * Previously a closed union type that required `as ChannelType` casts for
 * new channels (telegram, tiktok). Now a branded string so any channel
 * can be registered without modifying this file.
 *
 * Use `isKnownChannel()` when you need to narrow to a known channel.
 */
export type ChannelType = string & { readonly __brand?: 'ChannelType' };

/** All channel types currently supported by the platform. */
export const KNOWN_CHANNELS = [
  'facebook',
  'instagram',
  'zalo',
  'whatsapp',
  'livechat',
  'email',
  'telegram',
  'tiktok',
  'sms',
  'voice',
  'shopee',
] as const;

/** Narrow a string to a known channel type (compile-time guard). */
export type KnownChannelType = (typeof KNOWN_CHANNELS)[number];

/** Runtime check: is this string a known channel? */
export function isKnownChannel(type: string): type is KnownChannelType {
  return (KNOWN_CHANNELS as readonly string[]).includes(type);
}

export type SenderType = 'customer' | 'agent' | 'system' | 'bot';
export type MessageType =
  | 'text'
  | 'image'
  | 'file'
  | 'audio'
  | 'video'
  | 'location'
  | 'sticker'
  | 'template';

/**
 * Standard normalized payload — the single shape that flows through the
 * entire omni pipeline regardless of which provider originated the data.
 */
export interface OmniPayload {
  /** Internal tenant identifier (from CLS / JWT) */
  tenantId: string;

  /** Reference to the Channel document in our DB */
  channelId: string;

  /** Stable provider identifier (e.g. Page ID, OA ID) */
  channelAccount: string;

  /** Provider type enum */
  channelType: ChannelType;

  /** External user ID from the provider (e.g. FB psid, Zalo uid) */
  senderId: string;

  /** Who sent this message */
  senderType: SenderType;

  /** Semantic message type */
  messageType: MessageType;

  /** Text body (empty string for media-only messages) */
  content: string;

  /** Original media URL from the provider (may expire for Zalo) */
  mediaUrl?: string;

  /** Our proxied / cached media URL (stable, never expires) */
  mediaProxyUrl?: string;

  /** Freeform provider-specific extras (reactions, quick_replies, etc.) */
  metadata: Record<string, any>;

  /** Provider's message ID */
  externalMessageId: string;

  /** Provider's conversation / thread ID */
  externalConversationId: string;

  /** When the message was created at the provider */
  timestamp: Date;

  /**
   * Provider's original message creation timestamp.
   * Used as the canonical sort key for message ordering — immune to
   * server-side processing delays and queue re-ordering.
   * Falls back to `timestamp` if the provider does not supply it.
   */
  providerTimestamp: Date;

  /**
   * T07: trace ID for end-to-end log correlation.
   * Generated once per inbound webhook call (or per socket message) and
   * propagated through all downstream events and audit log entries.
   *
   * Generated by InboundProcessorService if not supplied by the adapter.
   * Format: UUID v4 (e.g. "550e8400-e29b-41d4-a716-446655440000").
   */
  correlationId?: string;
}

/**
 * OmniMessage — re-exported from the canonical definition.
 *
 * The full persisted message interface (with direction, senderName,
 * createdAt, updatedAt, etc.) lives in ./omni-message.ts.
 * This re-export preserves backward compatibility for any consumer
 * that imported OmniMessage from this file.
 *
 * @see ./omni-message.ts for the canonical definition.
 */
export type { OmniMessage } from './omni-message';
