/**
 * ChannelType — extensible channel identifier.
 *
 * Previously a closed union type that required `as ChannelType` casts for
 * new channels (telegram, tiktok). Now a branded string so any channel
 * can be registered without modifying this file.
 *
 * Use `isKnownChannel()` when you need to narrow to a known channel.
 */
export type ChannelType = string & { readonly __brand?: 'ChannelType' };

/**
 * Channels whose `senderId` IS the customer's phone number.
 *
 * WhatsApp delivers `msg.from` as the subscriber's MSISDN; the only phone in a
 * WhatsApp webhook's `metadata` is `phone_number_id` / `display_phone_number`,
 * which are the BUSINESS's number. Reading metadata for the customer's phone
 * therefore always came back empty, so phone-based identity resolution never
 * fired on the channel that needs it most, and the shadow contact it created
 * carried no phone at all — leaving the same person permanently split across
 * two records with nothing left to dedup on.
 */
const PHONE_IDENTITY_CHANNELS: ReadonlySet<string> = new Set(['whatsapp']);

/** True when this channel's sender id is a dialable phone number. */
export function isPhoneIdentityChannel(type: string): boolean {
  return PHONE_IDENTITY_CHANNELS.has(type);
}

/**
 * The customer's phone as carried by an inbound payload, before normalisation.
 *
 * Explicit metadata wins — a livechat visitor who typed their number is more
 * specific than a channel convention — with the sender id as the source of
 * truth on channels where it IS the number.
 */
export function resolvePayloadPhone(payload: {
  channelType: ChannelType;
  senderId: string;
  metadata?: Record<string, any>;
}): string | undefined {
  const explicit = payload.metadata?.phone;
  if (typeof explicit === 'string' && explicit.trim()) return explicit;
  return isPhoneIdentityChannel(payload.channelType)
    ? payload.senderId
    : undefined;
}

export type SenderType = 'customer' | 'agent' | 'system' | 'bot';
export type MessageType =
  | 'text'
  | 'image'
  | 'file'
  | 'audio'
  | 'video'
  | 'location'
  | 'sticker'
  | 'template';

/**
 * Standard normalized payload — the single shape that flows through the
 * entire omni pipeline regardless of which provider originated the data.
 */
export interface OmniPayload {
  /** Internal tenant identifier (from CLS / JWT) */
  tenantId: string;

  /** Reference to the Channel document in our DB */
  channelId: string;

  /** Stable provider identifier (e.g. Page ID, OA ID) */
  channelAccount: string;

  /** Provider type enum */
  channelType: ChannelType;

  /** External user ID from the provider (e.g. FB psid, Zalo uid) */
  senderId: string;

  /** Who sent this message */
  senderType: SenderType;

  /** Semantic message type */
  messageType: MessageType;

  /** Text body (empty string for media-only messages) */
  content: string;

  /** Original media URL from the provider (may expire for Zalo) */
  mediaUrl?: string;

  /** Our proxied / cached media URL (stable, never expires) */
  mediaProxyUrl?: string;

  /** Freeform provider-specific extras (reactions, quick_replies, etc.) */
  metadata: Record<string, any>;

  /** Provider's message ID */
  externalMessageId: string;

  /** Provider's conversation / thread ID */
  externalConversationId: string;

  /** When the message was created at the provider */
  timestamp: Date;

  /**
   * Provider's original message creation timestamp.
   * Used as the canonical sort key for message ordering — immune to
   * server-side processing delays and queue re-ordering.
   * Falls back to `timestamp` if the provider does not supply it.
   */
  providerTimestamp: Date;

  /**
   * Trace ID for end-to-end log correlation.
   * Generated once per inbound webhook call (or per socket message) and
   * propagated through all downstream events and audit log entries.
   *
   * Generated by InboundProcessorService if not supplied by the adapter.
   * Format: UUID v4 (e.g. "550e8400-e29b-41d4-a716-446655440000").
   */
  correlationId?: string;
}

/**
 * OmniMessage — re-exported from the canonical definition.
 *
 * The full persisted message interface (with direction, senderName,
 * createdAt, updatedAt, etc.) lives in ./omni-message.ts.
 * This re-export preserves backward compatibility for any consumer
 * that imported OmniMessage from this file.
 *
 * @see ./omni-message.ts for the canonical definition.
 */
export type { OmniMessage } from './omni-message';
